name: Deploy acquisition-builder service to Cloud Functions

# Worklfow triggered on push to acquisition-builder directory and by manual dispatch
on:
  push:
    paths:
      - 'acquisition-builder/**'
  workflow_dispatch:

# Define the deployment variables
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: acquisition-builder
  REGION: asia-south1
  SACCOUNT: ${{ secrets.GCP_SA_GEOCORE }}
  TOPIC: acquisition-builds
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Cloud Functions
        working-directory: ./acquisition-builder
        run: |
          gcloud functions deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --entry-point main \
            --service-account ${{ env.SACCOUNT }} \
            --runtime python39 \
            --trigger-topic ${{ env.TOPIC }}
