name: Deploy asset-create service to Cloud Functions

# Worklfow triggered on push to asset-create directory and by manual dispatch
on:
  push:
    paths:
      - 'asset-create/**'
  workflow_dispatch:

# Define the deployment variables
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: asset-create
  REGION: asia-south1
  SACCOUNT: ${{ secrets.GCP_SA_EVENTHANDLER }}
  EVENT: google.storage.object.finalize
  RESOURCE: terrascope-assets
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Cloud Functions
        working-directory: ./region-create
        run: |
          gcloud functions deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --entry-point main \
            --service-account ${{ env.SACCOUNT }} \
            --runtime python39 \
            --trigger-event "${{ env.EVENT }}" \
            --trigger-resource "${{ env.RESOURCE }}"
